### ISSUE TITLE
Make check failed to execute normally.

### ISSUE THREAD

**Issue by GYShit** [gssapi/gssproxy#69]
version info:
krb5: 1.19
gssproxy: 0.8.4
nss_wrapper: 1.1.11
openldap: 2.6.0
socket_wrapper: 1.1.9

When i run make check some errors occur:
```
./tests/runtests.py


To pass arguments to the test suite, use CHECKARGS:
    make check CHECKARGS='--debug-num=<num>'
A full set of available options can be seen with --help


Waiting for LDAP server to start...
krb5kdc: starting...
Traceback (most recent call last):
  File "/root/rpmbuild/BUILD/gssproxy-0.8.4/./tests/runtests.py", line 89, in runtests_main
    gproc, gpsocket = setup_gssproxy(testdir, gssproxyenv)
  File "/root/rpmbuild/BUILD/gssproxy-0.8.4/tests/testlib.py", line 766, in setup_gssproxy
    gssproxy_reload(testdir, gproc.pid, {
  File "/root/rpmbuild/BUILD/gssproxy-0.8.4/tests/testlib.py", line 801, in gssproxy_reload
    raise Exception("timed out while waiting for gssproxy to reload")
Exception: timed out while waiting for gssproxy to reload
Killing LDAP(559570)
Killing KDC(559579)
make: *** [Makefile:2248: check] Error 1
```

**Comment by simo5** [comment]
What distribution is this?
I fail to reproduce running as a user in Fedora 37

Can you reproduce when running as a regular user rather than root?

**Comment by GYShit** [comment]
> What distribution is this? I fail to reproduce running as a user in Fedora 37
> 
> Can you reproduce when running as a regular user rather than root?

**Comment by GYShit** [comment]
I find the problem.
The test suit can't run because of valgrind error, and now I can run make tests.
